### ISSUE TITLE
Error "Couldn't connect to API server, check logs" though mizu pods are running in mizu namespace

### ISSUE THREAD

**Issue by senthilrch** [up9inc/mizu#252]
**Describe the bug**
I installed mizu 0.12.2 in Macbook. Ran `mizu tap "^eric-mesh-gateways*"`. Got error `Couldn't connect to API server, check logs` though I could see mizu pods, service and daemonset running successfully in `mizu` namespace

```
eechens@EMB-Q6BUMD6N Bin % mizu tap "^eric-mesh-gateways*"
Mizu will store up to 200MB of traffic, old traffic will be cleared once the limit is reached.
Tapping pods in namespaces "mxe-senthil"
+eric-mesh-gateways-65d7667954-6x6wp
+eric-mesh-gateways-65d7667954-fkn5d
Couldn't connect to API server, check logs

Removing mizu resources
eechens@EMB-Q6BUMD6N Bin %
```

```
eechens@EMB-Q6BUMD6N ~ % kubectl get all -n mizu
NAME                               READY   STATUS    RESTARTS   AGE
pod/mizu-api-server                1/1     Running   0          6s
pod/mizu-tapper-daemon-set-bwk57   1/1     Running   0          5s
pod/mizu-tapper-daemon-set-zc4ws   1/1     Running   0          5s

NAME                      TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)   AGE
service/mizu-api-server   ClusterIP   10.110.86.225   <none>        80/TCP    6s

NAME                                    DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
daemonset.apps/mizu-tapper-daemon-set   2         2         2       2            2           <none>          6s
eechens@EMB-Q6BUMD6N ~ %
```

**To Reproduce**
1. Run mizu tap "^eric-mesh-gateways*"

**Expected behavior**
Expected mizu GUI to open in browser

**Logs**
[mizu_logs_2021_08_31__10_48_41.zip](https://github.com/up9inc/mizu/files/7081427/mizu_logs_2021_08_31__10_48_41.zip)

**Screenshots**
None

**Desktop (please complete the following information):**
 - OS: MacOS Catalina
 - Browser: Chrome

**Additional context**
- The cluster connectivity is over VPN.
- kubectl access to the cluster works fine

**Comment by RoyUP9** [comment]
Hi @senthilrch,
Thanks for reaching out.

After initial investigation, looking at the logs, it looks like the proxy is running but the mizu route doesn’t exist.

In order to continue the investigation and identify the problem, we’ve added more logs which will give us the needed information.
From your side please do the following steps, this should provide us with the data we need:
1. Install pre-release 0.12.5 (https://github.com/up9inc/mizu/releases/tag/0.12.5)
2. Run the command `API_SERVER_RETRIES=100 mizu tap "^eric-mesh-gateways*” --set dump-logs=true` (We’ve added the option to extend the retries count in order to give more time to debug the problem)
3. Try to reach the following url: http://localhost:8899/api/v1/namespaces/mizu/services/mizu-api-server/proxy/, do you see Mizu UI?
4. If not, do you see api server service in http://localhost:8899/api/v1/namespaces/mizu/services
5. If not, do you see mizu namespace in http://localhost:8899/api/v1/namespaces
6. If not, is the proxy working? navigate to http://localhost:8899/ and check if you see the endpoint list
7. if not, run with cli “kubectl proxy” do you see any errors? can you navigare now to http://localhost:8899/ and see list of all endpoints?
8. Provide us with the logs zip

Thanks!

**Comment by gadotroee** [comment]
Hi  @senthilrch, 
we recently released new version.
I'm closing this issue and and you are welcome to try the new version to see if your problem are still happening.
If needed, you can open new issue (with reference to this one) or re-open this.

Thanks.
