### ISSUE TITLE
Mizu API server was not ready in time

### ISSUE THREAD

**Issue by 5idu** [up9inc/mizu#612]
**Describe the bug**
Mizu API server was not ready in time.

**To Reproduce**
1. Run `mizu tap kieserver-proxy-7b6c685f44-4hdpv -n rule-ns`

**Expected behavior**
Can work normally.

**Screenshots**
![image](https://user-images.githubusercontent.com/26264096/148711809-02fc1312-94af-426a-9a10-bc9ff1253f64.png)

**Desktop (please complete the following information):**
 - OS: macOS Big Sur 11.5.1
[mizu_logs_2022_01_10__10_22_46.zip](https://github.com/up9inc/mizu/files/7836550/mizu_logs_2022_01_10__10_22_46.zip)

**Comment by RoyUP9** [comment]
Hey @5idu,
Thanks for reaching out.

I want to make sure it is not an issue in the proxy, so i can suggest you do the following:

1. You can Run the command `API_SERVER_RETRIES=100 mizu tap kieserver-proxy-7b6c685f44-4hdpv -n rule-ns` (We’ve added the option to extend the retries count in order to give more time to debug the problem)
2. Try to reach the following url: `http://localhost:8899/api/v1/namespaces/mizu/services/mizu-api-server/proxy/`, do you see Mizu UI?
3.  Can you try to run `kubectl proxy`, do you see any errors? Can you navigate now to the proxy served url and get response from k8s? - you should be able to see the "version" endpoint, in my laptop it is in port 8001 by default so I can go to `http://127.0.0.1:8001/version` and see k8s version details

Thanks!

**Comment by 5idu** [comment]
@RoyUP9 thanks reply!
i have change the mizu image location, but it still not work... below is the error message:
![image](https://user-images.githubusercontent.com/26264096/148743911-4b073c9a-b427-48aa-9ac2-cc4ad6391df8.png)
[mizu_logs_2022_01_10__17_27_25.zip](https://github.com/up9inc/mizu/files/7837862/mizu_logs_2022_01_10__17_27_25.zip)

**Comment by RoyUP9** [comment]
Hey @5idu,

I want to make sure that mizu-api-server service was created, so could you please do the following:

1. You can Run the command `API_SERVER_RETRIES=100 mizu tap kieserver-proxy-7b6c685f44-4hdpv -n rule-ns --set agent-image=5idu/mizu-main:0.21.0 --set dump-logs=true` (We’ve added the option to extend the retries count in order to give more time to debug the problem)
2. Run `kubectl get services -n mizu` and check if  mizu-api-server service was created.

Thanks!

**Comment by 5idu** [comment]
@RoyUP9 
below is the zip logs:

![image](https://user-images.githubusercontent.com/26264096/148748825-434929a5-5f8e-400e-ba04-ba77c78a3c06.png)
[mizu_logs_2022_01_10__18_07_46.zip](https://github.com/up9inc/mizu/files/7838059/mizu_logs_2022_01_10__18_07_46.zip)

**Comment by RoyUP9** [comment]
@5idu thx for the reply,

So i suspect that the issue is in the proxy, and I can suggest you do the following:

1. You can Run the same command as before: `API_SERVER_RETRIES=100 mizu tap kieserver-proxy-7b6c685f44-4hdpv -n rule-ns --set agent-image=5idu/mizu-main:0.21.0 --set dump-logs=true `
2. Try to reach the following url: `http://localhost:8899/api/v1/namespaces/mizu/services/mizu-api-server/proxy/`, do you see Mizu UI?
3. Can you try to run `kubectl proxy`, do you see any errors? Can you navigate now to the proxy served url and get response from k8s? - you should be able to see the "version" endpoint, in my laptop it is in port 8001 by default so I can go to `http://127.0.0.1:8001/version` and send us k8s version details

Thanks!

**Comment by 5idu** [comment]
hi @RoyUP9 
I am using `k3s` and `rancher` to build a `k8s` cluster and i tried the steps you said，the current situation is as follows:
1. Access `http://localhost:8899/api/v1/namespaces/mizu/services/mizu-api-server/proxy/`， response is same as step `3`.
2. my cluster other service can be accessed normally
![image](https://user-images.githubusercontent.com/26264096/148869213-f1ea492e-76b2-4914-98b1-52fb74375870.png)

3. but the mizu still can't access
![image](https://user-images.githubusercontent.com/26264096/148869283-7611a769-d482-448e-bc45-e453535e6d68.png)

Thanks!

**Comment by IgorGov** [comment]
Hi @5idu,
We didn't tested mizu on k3s. We will investigate this case and will try to find a solution for it.
I can see that there is communication issue when mizu tries to create a proxy and connect the "mizu agent" inside the cluster. We are currently working on a mizu "standalone" mode which should be released next week. You will be able to run `./mizu install` it will create all necessary k8s components inside your cluster, including the k8s service, which you will be able to connect to with your preferred method: ingress, load balancer, etc. You can find more info [here](https://github.com/up9inc/mizu/blob/develop/docs/INSTALL_STANDALONE.md).
If you like to try it now you can use our latest "pre-release" [0.21.45](https://github.com/up9inc/mizu/releases/tag/0.21.45)

**Comment by 5idu** [comment]
@IgorGov Thanks for reply.
I tried to use the `0.21.45` version of `mizu`, but there is a problem when run `mizu install`:

![image](https://user-images.githubusercontent.com/26264096/149049262-7e209dbc-09bb-41ee-818c-33b2f3a19c08.png)

I can't access the `gcr.io` images, so I try to change the address of the target image. How can I use the command to replace the image address used by `basenine` and `kratos`?
The command I am using now:
`mizu install --set agent-image=5idu/mizu-develop:0.21.45`

**Comment by 5idu** [comment]
> @IgorGov Thanks for reply. I tried to use the `0.21.45` version of `mizu`, but there is a problem when run `mizu install`:
> 
> ![image](https://user-images.githubusercontent.com/26264096/149049262-7e209dbc-09bb-41ee-818c-33b2f3a19c08.png)
> 
> I can't access the `gcr.io` images, so I try to change the address of the target image. How can I use the command to replace the image address used by `basenine` and `kratos`? The command I am using now: `mizu install --set agent-image=5idu/mizu-develop:0.21.45`

i change the source code config and recompile, then use the new cli to run the command `mizu install`, it's ok now!

![image](https://user-images.githubusercontent.com/26264096/149061583-b7744e57-1467-4f8c-af95-7c5300db2dd1.png)
